### ISSUE TITLE
Missing python dependency, jinja2

### ISSUE THREAD

**Issue by joo-jie** [Efinix-Inc/sapphire-soc-dt-generator#7]
Fail to generate the device tree file. Need to do the following before issuing the init.sh; 
1. sudo apt install python3-pip
2. pip3 install jinja2

**Comment by efxmnalim** [comment]
Add software dependencies section to readme file https://github.com/Efinix-Inc/sapphire-soc-dt-generator/commit/b00486d6d06082355517104e20fcbbfaee11167d.
